api_platform:
    title: Internal Tools API
    version: 1.0.0

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    graphql:
        enabled: false

